### ISSUE TITLE
A imagem base64 está sempre vindo um quadrado cinza, alguém já passou por isso?

### ISSUE THREAD

**Issue by lucaspelle1909** [nfephp-org/sped-pos#11]
Se eu pego o base64 e jogo no navegador, só aparece esse quadrado cinza com fundo preto

[](url)
![image](https://user-images.githubusercontent.com/54604676/108417399-afd4ce80-720e-11eb-9397-2a16dffbbc37.png)

**Comment by robmachado** [comment]
O que ??? pego base64 da imagem e jogo no navegador ??? 
Cara !! não entendi é NADA !!!

**Comment by lucaspelle1909** [comment]
Ok, de repente estou fazendo coisa errada kk, quando eu uso o modo base64 ele é em formato pdf ou imagem? pois se eu tento utilizar como pdf e abrir em uma nova guia para impressão ele dá erro carregar. Aí eu pensei que talvez viesse como uma imagem, aí eu tentei abrir em um formato de imagem qualquer no navegador jogando um link do tipo "data:image/png;base64, $base64" e abre essa imagem acima

**Comment by robmachado** [comment]
O sped-pos retorna dados BINARIOS com os comandos de impressora termica ESC/POS e não PDF nem imagem !!!

Se você quer um PDF use o sped-da !!
